debug: true


server:
  port: 8888

management:
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
  metrics:
    tags:
      application: ${spring.application.name}

spring:
  application:
    name: actuator
  mvc:
    view:
      suffix: .html
      prefix: /
  main:
    allow-bean-definition-overriding: true

feign:
  okhttp:
    enabled: true
  basePackages: com.wt.test.actuator

