debug: true

server:
  port: 8888

management:
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
  metrics:
    tags:
      application: ${spring.application.name}

spring:
  application:
    name: actuator
  mvc:
    view:
      suffix: .html
      prefix: /
  main:
    allow-bean-definition-overriding: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/qiyu?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password:

feign:
  okhttp:
    enabled: true
  basePackages: com.wt.test.actuator

mybatis-plus:
  mapper-locations: classpath*:/mapper/*.xml
  type-aliases-package: com.wt.test.actuator.entity